from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Callable, TYPE_CHECKING

if TYPE_CHECKING:
    from .entities import (
        Node, Job, ComplianceReport, ApiKey, User,
        RemediationEvent, Rule,
    )


class INodeRepository(ABC):
    @abstractmethod
    async def save(self, node: "Node") -> None: ...
    @abstractmethod
    async def find_by_id(self, id: str) -> "Node | None": ...
    @abstractmethod
    async def find_by_hostname(self, hostname: str) -> "Node | None": ...
    @abstractmethod
    async def find_all(self, filters: dict) -> list["Node"]: ...
    @abstractmethod
    async def update(self, node: "Node") -> None: ...
    @abstractmethod
    async def delete(self, id: str) -> None: ...


class IJobRepository(ABC):
    @abstractmethod
    async def save(self, job: "Job") -> None: ...
    @abstractmethod
    async def find_by_id(self, id: str) -> "Job | None": ...
    @abstractmethod
    async def find_all(self, limit: int) -> list["Job"]: ...
    @abstractmethod
    async def update(self, job: "Job") -> None: ...
    @abstractmethod
    async def append_log(self, job_id: str, entry: dict) -> None: ...


class IComplianceRepository(ABC):
    @abstractmethod
    async def save_report(self, report: "ComplianceReport") -> None: ...
    @abstractmethod
    async def find_by_node(self, node_id: str) -> list["ComplianceReport"]: ...
    @abstractmethod
    async def find_summary(self) -> list[dict]: ...
    @abstractmethod
    async def save_remediation(self, event: "RemediationEvent") -> None: ...
    @abstractmethod
    async def find_remediations(self, node_id: str) -> list["RemediationEvent"]: ...
    @abstractmethod
    async def find_all_remediations(self, limit: int) -> list["RemediationEvent"]: ...
    @abstractmethod
    async def find_remediation(self, id: str) -> "RemediationEvent | None": ...
    @abstractmethod
    async def update_remediation(self, event: "RemediationEvent") -> None: ...


class IApiKeyRepository(ABC):
    @abstractmethod
    async def save(self, key: "ApiKey") -> None: ...
    @abstractmethod
    async def find_by_hash(self, hash: str) -> "ApiKey | None": ...
    @abstractmethod
    async def find_all(self) -> list["ApiKey"]: ...
    @abstractmethod
    async def revoke(self, id: str) -> None: ...
    @abstractmethod
    async def revoke_by_user_id(self, user_id: str) -> None: ...
    @abstractmethod
    async def count_active(self) -> int: ...
    @abstractmethod
    async def touch_last_used(self, id: str) -> None: ...


class IUserRepository(ABC):
    @abstractmethod
    async def save(self, user: "User") -> None: ...
    @abstractmethod
    async def find_by_id(self, id: str) -> "User | None": ...
    @abstractmethod
    async def find_by_username(self, username: str) -> "User | None": ...
    @abstractmethod
    async def find_all(self) -> list["User"]: ...
    @abstractmethod
    async def update(self, user: "User") -> None: ...
    @abstractmethod
    async def count_active(self) -> int: ...


class IAuditRepository(ABC):
    @abstractmethod
    async def save(self, entry: dict) -> None: ...
    @abstractmethod
    async def find_recent(self, limit: int) -> list[dict]: ...


class IRuleRepository(ABC):
    @abstractmethod
    async def save(self, rule: "Rule") -> None: ...
    @abstractmethod
    async def find_by_id(self, id: str) -> "Rule | None": ...
    @abstractmethod
    async def find_by_control_id(self, cid: str) -> "Rule | None": ...
    @abstractmethod
    async def find_all(self, filters: dict) -> list["Rule"]: ...
    @abstractmethod
    async def update(self, rule: "Rule") -> None: ...
    @abstractmethod
    async def delete(self, id: str) -> None: ...


class ISSHClient(ABC):
    @abstractmethod
    async def test_connectivity(
        self, ip: str, port: int, user: str, key_path: str
    ) -> tuple[bool, str | None]: ...

    @abstractmethod
    async def run_command(
        self, ip: str, port: int, user: str, key_path: str, command: str
    ) -> tuple[str, str, int]: ...


class IPlaybookRunner(ABC):
    @abstractmethod
    def run(
        self,
        inventory_content: str,
        playbook: str,
        extra_vars: dict,
        tags: str | None,
        skip_tags: str | None,
    ): ...


class IPuppetClient(ABC):
    @abstractmethod
    async def trigger_run(self, node_fqdn: str, description: str) -> dict: ...
    @abstractmethod
    async def get_job_result(self, job_id: str) -> dict: ...
    @abstractmethod
    async def list_nodes(self) -> list[dict]: ...
    @abstractmethod
    async def get_node_report(self, node_fqdn: str) -> dict: ...
    @abstractmethod
    async def health(self) -> dict: ...


class IWazuhClient(ABC):
    @abstractmethod
    async def get_alerts(self, since: str, agent_name: str) -> list[dict]: ...
    @abstractmethod
    async def get_sca_results(self, agent_id: str, policy_id: str) -> list[dict]: ...
    @abstractmethod
    async def list_agents(self) -> list[dict]: ...
    @abstractmethod
    async def health(self) -> dict: ...


class IPlatformConfigRepository(ABC):
    @abstractmethod
    async def get(self, key: str) -> str | None: ...
    @abstractmethod
    async def set(self, key: str, value: str) -> None: ...
    @abstractmethod
    async def get_all(self) -> dict[str, str]: ...


class IEventBus(ABC):
    @abstractmethod
    def subscribe(self, event_name: str, handler: Callable) -> None: ...
    @abstractmethod
    def publish(self, event_name: str, payload: dict) -> None: ...
