#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
rpm -q net-snmp
systemctl is-enabled snmpd.service 2>/dev/null | grep 'enabled'
systemctl is-active snmpd.service 2>/dev/null | grep '^active'
