#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
sed -ri 's/(selinux|enforcing)=0\s*//g' /etc/default/grub
grub2-mkconfig -o /boot/grub2/grub.cfg
sed -ri 's/^SELINUX=.*/SELINUX=enforcing/' /etc/selinux/config
setenforce 1
