#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
gsettings writable org.gnome.desktop.session idle-delay
gsettings writable org.gnome.desktop.screensaver lock-delay
gsettings get org.gnome.desktop.screensaver lock-delay
gsettings get org.gnome.desktop.session idle-delay
