#!/usr/bin/env bash
# Generated by the SABC Compliance Platform — do not edit by hand.
shopt -s globstar 2>/dev/null || true
ip6tables -A INPUT -i lo -j ACCEPT
ip6tables -A OUTPUT -o lo -j ACCEPT
ip6tables -A INPUT -s ::1 -j DROP
