#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
systemctl stop named.service
dnf remove bind
systemctl stop named.service
systemctl mask named.service
