#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
rpm -q bluez
systemctl is-enabled bluetooth.service 2>/dev/null | grep 'enabled'
systemctl is-active bluetooth.service 2>/dev/null | grep '^active'
