#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
grep -P '^\h*set\h+superusers' /boot/grub2/grub.cfg /boot/grub2/user.cfg 2>/dev/null
grep -P '^\h*password' /boot/grub2/grub.cfg /boot/grub2/user.cfg 2>/dev/null
