#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
rpm -q squid
systemctl is-enabled squid.service 2>/dev/null | grep 'enabled'
systemctl is-active squid.service 2>/dev/null | grep '^active'
