#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
systemctl stop snmpd.service
dnf remove net-snmp
systemctl stop snmpd.service
systemctl mask snmpd.service
