#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
rpm -q httpd nginx
systemctl show httpd.socket httpd.service -p UnitFileState,ActiveState |
systemctl show nginx.service -p UnitFileState,ActiveState | grep -Pi
