#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
systemctl stop avahi-daaemon.service
systemctl stop avahi-daemon.socket
DEBIAN_FRONTEND=noninteractive apt-get -y purge avahi-daemon
