#!/usr/bin/env bash
# Generated by the SABC Compliance Platform — do not edit by hand.
shopt -s globstar 2>/dev/null || true
dpkg-query -s iptables-persistent
package 'iptables-persistent' is not installed and no information is available
