#!/usr/bin/env bash
# Generated by the SABC Compliance Platform — do not edit by hand.
shopt -s globstar 2>/dev/null || true
echo "Authorized use only. All activity may be monitored and reported." > /etc/issue.net
