#!/usr/bin/env bash
# Generated by the SABC Compliance Platform — do not edit by hand.
shopt -s globstar 2>/dev/null || true
grep -P 'pam_faillock\.so' /etc/pam.d/system-auth /etc/pam.d/password-auth
grep -P '^\h*(deny|unlock_time)' /etc/security/faillock.conf
