#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
systemctl stop httpd.socket httpd.service
dnf remove httpd
systemctl stop nginx.service
dnf remove httpd nginx
systemctl stop httpd.socket httpd.service
systemctl mask httpd.socket httpd.service
systemctl stop nginx.service
systemctl mask nginx.service
