#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
firewall-cmd --get-zone-of-interface=lo
firewall-cmd --list-all --zone="$(firewall-cmd --get-zone-of-interface=lo |
