#!/usr/bin/env bash
# Generated by the SABC Compliance Platform — do not edit by hand.
shopt -s globstar 2>/dev/null || true
systemctl stop avahi-daaemon.service
systemctl stop avahi-daemon.socket
dnf remove -y avahi-daemon
