#!/usr/bin/env bash
# Generated by the SABC Compliance Platform — do not edit by hand.
shopt -s globstar 2>/dev/null || true
setenforce 1
sed -ri 's/^SELINUX=.*/SELINUX=enforcing/' /etc/selinux/config
