#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
firewall-cmd --permanent --zone=trusted --add-interface=lo
firewall-cmd --zone=public --change-interface=lo
firewall-cmd --reload
