#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
grub2-setpassword
grub2-mkconfig -o /boot/grub2/grub.cfg   # BIOS
grub2-mkconfig -o /boot/efi/EFI/redhat/grub.cfg   # UEFI
