#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
systemctl stop vsftpd.service
dnf remove vsftpd
systemctl stop vsftpd.service
systemctl mask vsftpd.service
