#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
rpm -q ypserv
systemctl is-enabled ypserv.service 2>/dev/null | grep 'enabled'
systemctl is-active ypserv.service 2>/dev/null | grep '^active'
