#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
systemctl stop dovecot.socket dovecot.service cyrus-imapd.service
dnf remove dovecot cyrus-imapd
systemctl stop dovecot.socket dovecot.service cyrus-imapd.service
systemctl mask dovecot.socket dovecot.service cyrus-imapd.service
