#!/usr/bin/env bash
# Generated by the SABC Compliance Platform — do not edit by hand.
shopt -s globstar 2>/dev/null || true
firewall-cmd --get-default-zone
firewall-cmd --permanent --zone=$(firewall-cmd --get-default-zone) --get-target
