#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
systemctl is-active firewalld
systemctl is-enabled nftables 2>/dev/null || echo 'nftables service masked/inactive (managed by firewalld)'
