#!/usr/bin/env bash
# Generated by the SABC Compliance Platform — do not edit by hand.
shopt -s globstar 2>/dev/null || true
sed -ri 's/^ENCRYPT_METHOD.*/ENCRYPT_METHOD SHA512/' /etc/login.defs
authselect apply-changes
