#!/usr/bin/env bash
# Generated by the SABC Compliance Platform — do not edit by hand.
shopt -s globstar 2>/dev/null || true
firewall-cmd --permanent --zone=trusted --add-interface=lo
firewall-cmd --reload
