#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
gsettings writable org.gnome.desktop.media-handling automount
gsettings writable org.gnome.desktop.media-handling automount-open
gsettings get org.gnome.desktop.media-handling automount
gsettings get org.gnome.desktop.media-handling automount-open
