#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
systemctl stop nfs-server.service
dnf remove nfs-utils
systemctl stop nfs-server.service
systemctl mask nfs-server.service
