#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
systemctl stop cups.socket cups.service
dnf remove cups
systemctl stop cups.socket cups.service
systemctl mask cups.socket cups.service
