#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
systemctl stop dnsmasq.service
dnf remove dnsmasq
systemctl stop dnsmasq.service
systemctl mask dnsmasq.service
