#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
gsettings writable org.gnome.login-screen banner-message-enable
gsettings writable org.gnome.login-screen banner-message-text
gsettings get org.gnome.login-screen banner-message-enable
gsettings get org.gnome.login-screen banner-message-text
