#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
rpm -q avahi
systemctl is-enabled avahi-daemon.socket avahi-daemon.service 2>/dev/null |
systemctl is-active avahi-daemon.socket avahi-daemon.service 2>/dev/null |
