#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
systemctl stop bluetooth.service
dnf remove bluez
systemctl stop bluetooth.service
systemctl mask bluetooth.service
