#!/usr/bin/env bash
# Generated by the SABC Compliance Platform — do not edit by hand.
shopt -s globstar 2>/dev/null || true
ufw default deny incoming
ufw default deny outgoing
ufw default deny routed
