#!/usr/bin/env bash
# Generated by the SABC Compliance Platform — do not edit by hand.
shopt -s globstar 2>/dev/null || true
DEBIAN_FRONTEND=noninteractive apt-get -y purge dovecot-imapd dovecot-pop3d
