#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
rpm -q samba
systemctl is-enabled smb.service 2>/dev/null | grep 'enabled'
systemctl is-active smb.service 2>/dev/null | grep '^active'
