#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
authselect enable-feature with-faillock
authselect apply-changes
printf 'deny = 5\nunlock_time = 900\n' >> /etc/security/faillock.conf
