#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
systemctl stop avahi-daemon.socket avahi-daemon.service
dnf remove avahi
systemctl stop avahi-daemon.socket avahi-daemon.service
systemctl mask avahi-daemon.socket avahi-daemon.service
