#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
rpm -q rsync-daemon
systemctl is-enabled rsyncd.socket rsyncd.service 2>/dev/null | grep
systemctl is-active rsyncd.socket rsyncd.service 2>/dev/null | grep
