#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
rpm -q nfs-utils
systemctl is-enabled nfs-server.service 2>/dev/null | grep 'enabled'
systemctl is-active nfs-server.service 2>/dev/null | grep '^active'
