#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
systemctl stop dhcpd.service dhcpd6.service
dnf remove dhcp-server
systemctl stop dhcpd.service dhcpd6.service
systemctl mask dhcpd.service dhcpd6.service
