#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
rpm -q autofs
systemctl is-enabled autofs.service 2>/dev/null | grep 'enabled'
systemctl is-active autofs.service 2>/dev/null | grep '^active'
