#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
rpm -q bind
systemctl is-enabled named.service 2>/dev/null | grep 'enabled'
systemctl is-active named.service 2>/dev/null | grep '^active'
