#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
rpm -q dhcp-server
systemctl is-enabled dhcpd.service dhcpd6.service 2>/dev/null | grep
systemctl is-active dhcpd.service dhcpd6.service 2>/dev/null | grep
