#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
systemctl stop rsyncd.socket rsyncd.service
dnf remove rsync-daemon
systemctl stop rsyncd.socket rsyncd.service
systemctl mask rsyncd.socket rsyncd.service
