#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
rpm -q dnsmasq
systemctl is-enabled dnsmasq.service 2>/dev/null | grep 'enabled'
systemctl is-active dnsmasq.service 2>/dev/null | grep '^active'
