#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
systemctl stop autofs.service
dnf remove autofs
systemctl stop autofs.service
systemctl mask autofs.service
