#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
rpm -q cups
systemctl is-enabled cups.socket cups.service 2>/dev/null | grep 'enabled'
systemctl is-active cups.socket cups.service 2>/dev/null | grep '^active'
