#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
rpm -q dovecot cyrus-imapd
systemctl is-enabled dovecot.socket dovecot.service cyrus-imapd.service
systemctl is-active dovecot.socket dovecot.service cyrus-imapd.service
