#!/usr/bin/env bash
# Generated by the SABC Compliance Platform — do not edit by hand.
shopt -s globstar 2>/dev/null || true
dpkg-query -W -f='${binary:Package}\t${Status}\t${db:Status-Status}\n' prelink
