#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
systemctl stop ypserv.service
dnf remove ypserv
systemctl stop ypserv.service
systemctl mask ypserv.service
