#!/usr/bin/env bash
# Generated by CRICLO — do not edit by hand.
shopt -s globstar 2>/dev/null || true
systemctl stop squid.service
dnf remove squid
systemctl stop squid.service
systemctl mask squid.service
