#!/usr/bin/env bash
# Generated by the SABC Compliance Platform — do not edit by hand.
shopt -s globstar 2>/dev/null || true
grep -P 'pam_pwhistory\.so' /etc/pam.d/system-auth /etc/pam.d/password-auth
