from __future__ import annotations
from functools import lru_cache
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    # Server
    port: int = 3000
    host_ip: str = ""            # Platform host's LAN IP; auto-detected when blank
    cors_origins: list[str] = [
        "http://localhost",
        "http://localhost:80",
        "http://localhost:5173",
        "http://localhost:4173",
        "http://127.0.0.1",
        "http://127.0.0.1:80",
    ]

    # Storage
    db_path: str = "./data/platform.db"
    # Full async DSN — overrides db_path when set.
    # SQLite (default):   leave blank
    # PostgreSQL:         postgresql+asyncpg://sabc:secret@postgres:5432/sabc
    database_url: str = ""
    ssh_key_path: str = "./keys/ansible_id_rsa"
    ansible_dir: str = "./ansible"
    packages_dir: str = "./packages"
    # Directory holding the frontend's TLS cert/key (server.crt / server.key).
    # Shared with the frontend container via the frontend-certs Docker volume so
    # an operator can install a CA-signed certificate through the UI. The
    # frontend's entrypoint watches this directory and reloads nginx on change.
    tls_certs_dir: str = "/app/certs"

    # JWT (username/password auth)
    jwt_secret: str = "change-me-in-production-use-random-32-chars"
    jwt_algorithm: str = "HS256"
    jwt_expire_hours: int = 24

    # Puppet
    # Which Puppet edition the platform integrates with:
    #   "enterprise" — Puppet Enterprise (PE Advanced). Uses the commercial
    #                  RBAC + Node Classifier HTTP APIs for node-group sync.
    #   "core"       — open-source Puppet (Puppet Core / puppet-agent +
    #                  puppetserver). Those PE-only APIs do not exist, so
    #                  classification is done with an External Node Classifier
    #                  (ENC) generated by the platform and deployed to the master
    #                  over SSH. This is the no-cost production path.
    puppet_edition: str = "enterprise"
    puppet_master_host: str | None = None
    puppet_master_port: int = 8143
    puppet_rbac_port: int = 4433
    puppet_admin_user: str = "admin"
    puppet_admin_pass: str | None = None
    puppet_token_lifetime: int = 1296000
    puppet_token_rotate_seconds: int = 43200
    # Puppet Core ENC deployment: where the ENC script + data file live on the
    # master, and how to reach it over SSH (key reuses the Ansible SSH key).
    puppet_core_enc_dir: str = "/etc/puppetlabs/puppet/enc"
    puppet_core_ssh_user: str = "root"
    puppet_core_default_environment: str = "production"

    # Detection agent webhook (the custom lightweight detection plane).
    # Comma-separated list of IPs/CIDRs allowed to POST /api/webhooks/detection.
    # Empty = allow any source that presents a valid API key.
    detection_webhook_source_ip: str | None = None
    # Shared API key presented by detection agents in the X-API-Key header.
    # When unset the webhook is DISABLED (closed by default) — no event is ever
    # processed without an explicitly configured key. Auto-generated and stored
    # in platform_config the first time a detection agent is installed.
    detection_webhook_api_key: str | None = None

    # Collection
    collector_interval_seconds: int = 300

    # Default OS package repository base URL used for node groups that don't set
    # their own (the "server default repository"). Blank → leave OS defaults.
    default_package_repo_url: str = ""

    # Closed-loop remediation
    # Max nodes remediated concurrently when the loop targets a whole node group
    # (bounds simultaneous SSH/Puppet runs).
    closed_loop_concurrency: int = 4

    # Offline AI assistant (Ollama)
    ollama_url: str = "http://localhost:11434"
    ollama_model: str = "llama3"

    # Features
    swagger_enabled: bool = True

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
    )


@lru_cache
def get_settings() -> Settings:
    return Settings()
